apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcp-client
  labels:
    app: hcp-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcp-client
  template:
    metadata:
      labels:
        app: hcp-client
    spec:
      imagePullSecrets:
      - name: dockerrochedcacc
      volumes:
      - name: nginx-hcp
        configMap:
          name: nginx-hcp
          items:
          - key: hcp.conf
            path: hcp.conf
      containers:
      - name: hcp-client
        imagePullPolicy: Always
        image: docker.rochedc.accentureanalytics.com/dockadmin/hcp-client
        volumeMounts:
        - name: nginx-hcp
          mountPath: /etc/nginx/conf.d
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
        env:
        - name: NODE_PATH
          valueFrom:
            configMapKeyRef:
              name: hcp-client
              key: NODE_PATH
        - name: REACT_APP_API_VERSION
          valueFrom:
            configMapKeyRef:
              name: hcp-client
              key: REACT_APP_API_VERSION
        - name: REACT_APP_API_ROOT
          valueFrom:
            configMapKeyRef:
              name: hcp-client
              key: REACT_APP_API_ROOT
        - name: REACT_APP_HCP_ENV
          valueFrom:
            configMapKeyRef:
              name: hcp-client
              key: REACT_APP_HCP_ENV
        - name: REACT_APP_GIGYA_TOKEN
          valueFrom:
             secretKeyRef:
              name: hcp-client-secret
              key: REACT_APP_GIGYA_TOKEN
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: hcp-client
spec:
  selector:
    app: hcp-client
  ports:
  - protocol: TCP
    name: hcp-client
    port: 3000
    nodePort: 30801
  type: NodePort
