export const mockTheme = {
  animations: { fadeIn: '', fadeOut: '' },
  BASE_FONT_SIZE: 16,
  borderRadius: [
    '0.1875rem',
    '0.375rem',
    '0.5rem',
    '1.25rem',
    '6.25rem',
    '50%',
  ],
  boxShadow: () => ({}),
  boxShadows: {
    base: '',
    one: '',
    two: '',
    three: '',
    four: '',
    five: '',
    six: '',
    seven: '',
    eight: '',
    nine: '',
  },
  breakpoints: [1024, 1440],
  colors: {
    clear: '',
    white: '',
    black: '',
    silverLight: '',
    silver: '',
    silverMedium: '',
    silverDark: '',
    grayLight: '',
    grayMedium: '',
    gray: '',
    grayLighter: '',
    grayDark: '',
    charcoal: '',
    green: '',
    turqoise: '',
    lighterTurqoise: '',
    lightTurqoise: '',
    lightGreen: '',
    transparentGreen: '',
    brandBlue: '',
    brandBlueDark: '',
    blue: '',
    cyan: '',
    transparentCyan: '',
    blueMarineAlpha: '',
    blueMarineAlpha5: '',
    blueMarineAlpha15: '',
    darkBlueMarine: '',
    blueMarine: '',
    blueMarine5: '',
    blueLight: '',
    blueVeryLight: '',
    blueFaded: '',
    quartzBlue: '',
    basalBlue: '',
    lavender: '',
    red: '',
    redLight: '',
    redLighter: '',
    redPastel: '',
    orangeLight: '',
    darkestGray: '',
    trafficRed: '',
    trafficRed2: '',
    trafficOrange: '',
    trafficGreen: '',
    darkOrange: '',
    transparentGrayMedium: '',
    transparentGrayLight: '',
    transparentGrayDark: '',
    transparentBlack: '',
    carb: '',
    heroGradient: '',
  },
  fontSize: {
    graphLabel: '',
    label: '',
    caption: '',
    p: '',
    subheading: '',
    title: '',
    headline: '',
    display1: '',
    display2: '',
    display3: '',
    display4: '',
  },
  fontSizes: [8, 12, 14, 16, 20, 24, 34, 45, 56, 112],
  fontWeights: {
    semiBold: '',
    ultraBold: '',
    bold: '',
    regular: '',
  },
  letterSpacing: {
    small: '',
    medium: '',
    large: '',
  },
  space: ['', '', '', '', '', '', ''],
  spacing: {
    zer0: '',
    one: '',
    two: '',
    three: '',
    four: '',
    five: '',
    six: '',
  },
  textStyles: '',
  transitions: {
    default: '',
    fast: '',
    medium: '',
    slow: '',
    enter: '',
    exit: '',
  },
  zIndexes: {
    hidden: 1,
    base: 1,
    foreground: 1,
    overlay: 1,
    popover: 1,
    routeNav: 1,
    modal: 1,
    alert: 1,
  },
};
