apiVersion: apps/v1
kind: Deployment
metadata:
  name: seed-example
  labels:
    app: seed-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seed-example
  template:
    metadata:
      labels:
        app: seed-example
    spec:
      imagePullSecrets:
      - name: dockerrochedcacc
      volumes:
      - name: nginx-pp
        configMap:
          name: nginx-pp
          items:
          - key: pp.conf
            path: pp.conf
      containers:
      - name: seed-example
        imagePullPolicy: Always
        image: docker.rochedc.accentureanalytics.com/dockadmin/seed-example
        volumeMounts:
        - name: nginx-pp
          mountPath: /etc/nginx/conf.d
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
        env:
        - name: NODE_PATH
          valueFrom:
            configMapKeyRef:
              name: seed-example
              key: NODE_PATH
        - name: REACT_APP_API_VERSION
          valueFrom:
            configMapKeyRef:
              name: seed-example
              key: REACT_APP_API_VERSION
        - name: REACT_APP_API_ROOT
          valueFrom:
            configMapKeyRef:
              name: seed-example
              key: REACT_APP_API_ROOT
        - name: REACT_APP_HCP_ENV
          valueFrom:
            configMapKeyRef:
              name: seed-example
              key: REACT_APP_HCP_ENV
        - name: REACT_APP_GIGYA_TOKEN
          valueFrom:
             secretKeyRef:
              name: seed-example-secret
              key: REACT_APP_GIGYA_TOKEN
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: seed-example
spec:
  selector:
    app: seed-example
  ports:
  - protocol: TCP
    name: seed-example
    port: 3000
    nodePort: 30801
  type: NodePort
