import { Permissions } from './permissions.types';

export const PERMISSIONS: Permissions = {
  PATIENT: 'ROLE_PATIENT',
  DATA_DOWNLOAD: 'ROLE_DATA_DOWNLOAD',
  GLUCOSE_STATISTICS: 'ROLE_EXPORT_GLUCOSE_STATISTICS',
  STRIP_MNG_PATIENT: 'ROLE_STRIP_MNG_PATIENT',
  HOME_DELIVERY_PATIENT: 'ROLE_DELIVERY_MGMT_PATIENT',
};
