import { convertISOToJsGMT } from 'src/domains/diagnostics/utils';

export const profileChangesMock = [
  {
    date: convertISOToJsGMT('2018-03-09 16:43:00 GMT+0000'),
    cbrf: 0,
    profile: '1',
    remark: '1 - 2',
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-09 16:43:00 GMT+0000'),
    cbrf: 0,
    profile: '4',
    remark: '4 - 5',
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
];

export const profileWeeklyChangesMock = {
  basals: profileChangesMock,
};

export const insulinBasalsMock = [
  {
    date: convertISOToJsGMT('2018-03-07 00:00:00 GMT+0000'),
    cbrf: 0.7,
    profile: '1',
    remark: null,
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-07 05:45:00 GMT+0000'),
    cbrf: 0.9,
    profile: '1',
    remark: null,
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-07 16:00:00 GMT+0000'),
    cbrf: 1.1,
    profile: '1',
    remark: null,
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-07 17:38:00 GMT+0000'),
    cbrf: 1.1,
    profile: '1',
    remark: 'Pause',
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-07 21:00:00 GMT+0000'),
    cbrf: 0.36,
    profile: '1',
    remark: null,
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-07 21:18:00 GMT+0000'),
    cbrf: 0,
    profile: '1',
    remark: 'Stop',
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-07 21:19:00 GMT+0000'),
    cbrf: 0.36,
    profile: '1',
    remark: 'Run',
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-07 21:35:00 GMT+0000'),
    cbrf: 0,
    profile: '1',
    remark: 'Stop',
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-07 21:43:00 GMT+0000'),
    cbrf: 0.36,
    profile: '1',
    remark: 'Run',
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-08 00:00:00 GMT+0000'),
    cbrf: 0.7,
    profile: '1',
    remark: null,
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-08 05:45:00 GMT+0000'),
    cbrf: 0.9,
    profile: '1',
    remark: null,
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-08 16:00:00 GMT+0000'),
    cbrf: 1.1,
    profile: '1',
    remark: null,
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-08 21:00:00 GMT+0000'),
    cbrf: 0.36,
    profile: '1',
    remark: null,
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-09 00:00:00 GMT+0000'),
    cbrf: 0.7,
    profile: '1',
    remark: null,
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-09 05:45:00 GMT+0000'),
    cbrf: 0.9,
    profile: '1',
    remark: null,
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-09 16:00:00 GMT+0000'),
    cbrf: 1.1,
    profile: '1',
    remark: null,
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-09 16:43:00 GMT+0000'),
    cbrf: 0,
    profile: '1',
    remark: '1 - 2',
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-09 16:43:00 GMT+0000'),
    cbrf: 0.4,
    profile: '2',
    remark: '1 - 2',
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-09 23:07:00 GMT+0000'),
    cbrf: 0.28,
    profile: '2',
    remark: null,
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: '70%',
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-09 23:59:00 GMT+0000'),
    cbrf: 0,
    profile: '1',
    remark: 'TBR End',
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-10 00:00:00 GMT+0000'),
    cbrf: 0.35,
    profile: '2',
    remark: 'dur 0:07 h',
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: '70%',
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-10 00:07:00 GMT+0000'),
    cbrf: 0,
    profile: '1',
    remark: 'TBR End',
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-10 00:07:00 GMT+0000'),
    cbrf: 0.5,
    profile: '2',
    remark: 'TBR End',
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
  {
    date: convertISOToJsGMT('2018-03-10 10:00:00 GMT+0000'),
    cbrf: 0.4,
    profile: '2',
    remark: null,
    virtual: null,
    tsb: null,
    tsbDiffMins: null,
    tbrdec: null,
    tbrinc: null,
  },
];
